[sugars.honey]
name = "Honey"
gravity_points = 35
fermentability = 1.00

[sugars.table_sugar]
name = "Table Sugar"
gravity_points = 46
fermentability = 1.00

[acids.tartaric]
name = "Tartaric Acid"
strength = 1.00

[acids.citric]
name = "Citric Acid"
strength = 0.90
