[[items]]
name = "Honey"
category = "sweetener"
sugar_content = 82.0

[[items]]
name = "Maple Syrup"
category = "sweetener"
sugar_content = 67.0

[[items]]
name = "Apple Juice"
category = "juice"
sugar_content = 10.4

[[items]]
name = "Orange Juice"
category = "juice"
sugar_content = 9.0

[[items]]
name = "White Sugar"
category = "sweetener"
sugar_content = 100.0
