[package]
name = "mazerion-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "mazerion"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
mazerion-core = { path = "../core" }
mazerion-calculators = { path = "../calculators" }
mazerion-config = { path = "../config" }
mazerion-gui = { path = "../gui" }
mazerion-tui = { path = "../tui" }
anyhow = { workspace = true }
