[package]
name = "mazerion-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rust_decimal = { workspace = true }
rust_decimal_macros = "1.36"
serde = { workspace = true }
thiserror = { workspace = true }
linkme = "0.3"
