[package]
name = "mazerion-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rust_decimal = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
linkme = "0.3.35"
